// <auto-generated />
using System;
using Matches.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Matches.Infrastructure.Migrations
{
    [DbContext(typeof(MatchContext))]
    [Migration("20200307135942_AddMatchesAndMatchStatus")]
    partial class AddMatchesAndMatchStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:match.matchseq", "'matchseq', 'match', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:match.playerseq", "'playerseq', 'match', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:match.teamseq", "'teamseq', 'match', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teams.Domain.Aggregates.MatchAggregate.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "matchseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "match")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnName("UtcDate1")
                        .HasColumnType("datetime2");

                    b.Property<int?>("_awayTeamId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("_homeTeamId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("_matchStatusId")
                        .HasColumnName("MatchStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("_utcDate")
                        .HasColumnName("UtcDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StatusId");

                    b.HasIndex("_awayTeamId");

                    b.HasIndex("_homeTeamId");

                    b.ToTable("matches","match");
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.MatchAggregate.MatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("matchstatus","match");
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.MatchAggregate.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.TeamAggregate.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "playerseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "match")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("players","match");
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.TeamAggregate.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "teamseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "match")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("teams","match");
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.MatchAggregate.Match", b =>
                {
                    b.HasOne("Teams.Domain.Aggregates.MatchAggregate.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId");

                    b.HasOne("Teams.Domain.Aggregates.MatchAggregate.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("Teams.Domain.Aggregates.MatchAggregate.MatchStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("Teams.Domain.Aggregates.MatchAggregate.Team", null)
                        .WithMany()
                        .HasForeignKey("_awayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teams.Domain.Aggregates.MatchAggregate.Team", null)
                        .WithMany()
                        .HasForeignKey("_homeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Teams.Domain.Aggregates.MatchAggregate.Score", "Score", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .HasColumnType("int");

                            b1.Property<int>("AwayTeam")
                                .HasColumnType("int");

                            b1.Property<int>("HomeTeam")
                                .HasColumnType("int");

                            b1.Property<string>("Winner")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });
                });

            modelBuilder.Entity("Teams.Domain.Aggregates.TeamAggregate.Player", b =>
                {
                    b.HasOne("Teams.Domain.Aggregates.TeamAggregate.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
