version: '3.4'

services:
  matches.api:
    image: ${DOCKER_REGISTRY-}matchesapi
    build:
      context: .
      dockerfile: Services/Matches/Matches.API/Dockerfile

  phrases.api:
    image: ${DOCKER_REGISTRY-}phrasesapi
    build:
      context: .
      dockerfile: Services/Phrases/Phrases.API/Dockerfile


  web.httpaggregator:
    image: ${DOCKER_REGISTRY-}webhttpaggregator
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff/Web.HttpAggregator/Dockerfile


  useraccess.api:
    image: ${DOCKER_REGISTRY-}useraccessapi
    build:
      context: .
      dockerfile: Services/UserAccess/UserAccess.API/UserAccess.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
        - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5673:5673
        - 5672:5672
        - 15672:15672
