// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Phrases.Infrastructure.Persistence;

namespace Phrases.Infrastructure.Migrations
{
    [DbContext(typeof(PhraseContext))]
    internal class PhraseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phrases.Domain.Phrase.Phrase", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("_dateCreated")
                    .HasColumnName("DateCreated")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("_dateDeleted")
                    .HasColumnName("DateDeleted")
                    .HasColumnType("datetime2");

                b.Property<string>("_description")
                    .IsRequired()
                    .HasColumnName("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("_isDeleted")
                    .HasColumnName("IsDeleted")
                    .HasColumnType("bit");

                b.Property<Guid>("_matchId")
                    .HasColumnName("MatchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("_positive")
                    .HasColumnName("Positive")
                    .HasColumnType("bit");

                b.Property<int>("_score")
                    .HasColumnName("Score")
                    .HasColumnType("int");

                b.Property<Guid>("_teamId")
                    .HasColumnName("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("phrases", "phrase");
            });
#pragma warning restore 612, 618
        }
    }
}