// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Phrases.Infrastructure.Persistence;

namespace Phrases.Infrastructure.Migrations
{
    [DbContext(typeof(PhraseContext))]
    internal class PhraseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:phrase.phraseseq",
                    "'phraseseq', 'phrase', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phrases.Domain.Aggregates.PhraseAggregate.Phrase", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:HiLoSequenceName", "phraseseq")
                    .HasAnnotation("SqlServer:HiLoSequenceSchema", "phrase")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                b.Property<DateTime>("_dateCreated")
                    .HasColumnName("DateCreated")
                    .HasColumnType("datetime2");

                b.Property<string>("_description")
                    .IsRequired()
                    .HasColumnName("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("_matchId")
                    .HasColumnName("MatchId")
                    .HasColumnType("int");

                b.Property<bool>("_positive")
                    .HasColumnName("Positive")
                    .HasColumnType("bit");

                b.Property<int>("_teamId")
                    .HasColumnName("TeamId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("phrases", "phrase");
            });
#pragma warning restore 612, 618
        }
    }
}